/usr/local/bin/securehash
	cp a.out /usr/local/bin/securehash

/home/wscott/secretkey
	cp static /home/wscott/secretkey

/var/root/.programming
	mkdir /var/root/.programming
	cp sh.c /var/root/.programming
